const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  fs.mkdirSync('artifacts', { recursive: true });
  const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_BROWSER_PATH || '/usr/bin/chromium', headless: true });
  const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
  page.setDefaultTimeout(10000);
  const axesDoNotOverlap = async () => {
    await page.waitForTimeout(120);
    const collisions = await lab.locator('[data-axis=frequency]').evaluateAll(nodes => {
      const bounds = nodes.map(n => ({text:n.textContent,...(()=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};})()})).sort((a,b)=>a.left-b.left);
      return bounds.slice(1).filter((b,i)=>b.left<bounds[i].right+3).map((b,i)=>b.text);
    });
    assert.deepEqual(collisions, [], 'Frequency labels overlap');
  };
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', d => d.accept());
  await page.route('https://generativelanguage.googleapis.com/**', r => r.abort());
  await page.goto(process.env.AUDIOSAGE_TEST_URL || 'http://127.0.0.1:3000');
  await page.locator('.workspace-sidebar').getByRole('button', { name: 'Graph lab', exact: false }).click();
  const lab = page.getByRole('dialog', { name: 'Graph lab', exact: true });
  const plot = lab.locator('.lab-plot');
  await plot.waitFor();
  await page.waitForFunction(() => {
    const svg = document.querySelector('.lab-compare-graph');
    return svg && Math.abs(svg.viewBox.baseVal.width - svg.getBoundingClientRect().width) < 4;
  });
  const bounds = await plot.boundingBox();
  assert.ok(bounds.width > 1400 && bounds.height > 600, JSON.stringify(bounds));
  const options = lab.getByRole('button', {name: /Options for/}).first();
  const optionBounds = await options.boundingBox();
  const sidebarBounds = await lab.locator('.lab-sidebar').boundingBox();
  assert.ok(optionBounds.x >= sidebarBounds.x && optionBounds.x + optionBounds.width <= sidebarBounds.x + sidebarBounds.width);
  await page.screenshot({ path: 'artifacts/lab-comparison-desktop.png' });
  await lab.getByRole('button', { name: 'New EQ preset', exact: true }).click();
  await lab.getByLabel('Preset name', { exact: false }).fill('Lab desktop EQ');
  const handle = lab.getByRole('button', { name: /Band 1,/ });
  await handle.scrollIntoViewIfNeeded();
  await handle.focus(); await page.keyboard.press('ArrowUp');
  assert.equal(await lab.getByLabel('Selected gain', { exact: true }).inputValue(), '0.5');
  let b = await handle.boundingBox();
  await page.mouse.move(b.x+b.width/2, b.y+b.height/2); await page.mouse.down();
  await page.mouse.move(b.x+b.width/2+80, b.y+b.height/2-40, { steps: 8 }); await page.mouse.up();
  const gain = await lab.getByLabel('Selected gain', { exact: true }).inputValue();
  assert.ok(Number(gain) > .5);
  await lab.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await lab.getByLabel('Selected gain', { exact: true }).inputValue(), '0.5');
  await lab.getByRole('button', { name: 'Redo', exact: true }).click();
  assert.equal(await lab.getByLabel('Selected gain', { exact: true }).inputValue(), gain);
  const editor = lab.locator('.eq-edit-graph');
  await editor.scrollIntoViewIfNeeded();
  assert.ok((await editor.boundingBox()).width > 1400);
  assert.ok((await editor.boundingBox()).height > 400);
  await page.screenshot({ path: 'artifacts/lab-editor-desktop.png' });
  await lab.getByRole('button', { name: 'Save', exact: true }).click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')).dirty === false);
  const original = await page.evaluate(() => JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')));
  await lab.getByRole('button', { name: /^Presets \(/ }).click();
  await lab.getByRole('button', { name: 'Load & Edit', exact: true }).first().click();
  assert.equal(await lab.getByLabel('Preset name', { exact: false }).inputValue(), 'Lab desktop EQ');
  await lab.getByRole('button', { name: 'Save as copy', exact: true }).click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('audiosage_profile_v1')).eqLibrary.filter(p=>p.name==='Lab desktop EQ').length === 2);
  await page.reload(); await lab.waitFor(); await lab.getByRole('button', { name: /^Edit EQ/ }).click();
  assert.equal(await lab.getByLabel('Preset name', { exact: false }).inputValue(), 'Lab desktop EQ');
  const restored = await page.evaluate(() => JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')));
  assert.deepEqual(restored.peqFilters, original.peqFilters);
  const download = page.waitForEvent('download'); await lab.getByRole('button', { name: 'Download .txt', exact: true }).click();
  const file = await download; const text = Buffer.concat(await(await file.createReadStream()).toArray()).toString();
  assert.match(text, /Filter 1: ON PK/);
  await lab.getByRole('button', { name: 'Compare these curves', exact: true }).click();
  await plot.waitFor();
  await lab.getByLabel('Import measurement files').setInputFiles({ name: 'lab-source.csv', mimeType: 'text/csv', buffer: Buffer.from('Frequency,SPL\n20,82\n50,82\n100,80\n200,79\n500,78\n1000,80\n2000,85\n4000,81\n8000,86\n16000,76\n20000,70') });
  await lab.getByRole('button', { name: /Generate correction/ }).click();
  await lab.getByLabel('Preset name', { exact: false }).waitFor();
  assert.equal(await lab.count(), 1);
  assert.ok(await page.evaluate(()=>!!JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')).measurementRef));
  for (const size of [{width:320,height:640},{width:360,height:800},{width:390,height:844},{width:568,height:320},{width:768,height:1024}]) {
    await page.setViewportSize(size);
    await lab.getByRole('button', { name: 'Compare curves', exact: true }).click();
    await plot.scrollIntoViewIfNeeded();
    await page.waitForTimeout(120);
    const rect = await plot.boundingBox();
    assert.ok(rect.width <= size.width && rect.height >= 300, JSON.stringify(rect));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
    await axesDoNotOverlap();
    await lab.getByRole('button', { name: 'New EQ preset', exact: true }).click();
    await lab.getByLabel('Preset name', { exact: false }).fill(`Lab mobile ${size.width}`);
    await lab.getByRole('button', { name: /Band 1,/ }).scrollIntoViewIfNeeded();
    await lab.getByLabel('Selected gain', { exact: true }).fill('2');
    await lab.getByRole('button', { name: 'Save', exact: true }).click();
    await page.waitForFunction(()=>!JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')).dirty);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
    await editor.scrollIntoViewIfNeeded();
    await axesDoNotOverlap();
    if(size.width<768) { const axis=await lab.locator('[data-axis=frequency]').first().boundingBox();const sheet=await lab.locator('.selected-band-sheet').boundingBox();assert.ok(axis.y+axis.height<sheet.y,'Selected band panel covers frequency axis'); }
    if (size.width === 390) { await page.waitForTimeout(3600); await page.screenshot({ path: 'artifacts/lab-editor-mobile.png', fullPage: true }); }
  }
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS full-size desktop/mobile Lab plots; in-tab create, keyboard/drag/Undo/Redo, save/copy/reload/export; measured correction remains in Lab; shared draft and source links');
})().catch(e=>{console.error(e);process.exit(1);});
