const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_BROWSER_PATH||'/usr/bin/chromium',headless:true});
 const page=await browser.newPage({viewport:{width:360,height:800},hasTouch:true,deviceScaleFactor:2});
 page.on('dialog',d=>d.accept());const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.AUDIOSAGE_TEST_URL||'http://127.0.0.1:3000');
 await page.getByRole('button',{name:'Open navigation',exact:true}).click();
 await page.locator('.workspace-sidebar').filter({visible:true}).getByRole('button',{name:'Graph lab',exact:false}).click();
 const lab=page.getByRole('dialog',{name:'Graph lab',exact:true});await lab.getByRole('button',{name:'New EQ preset',exact:true}).click();
 const graph=lab.locator('.eq-edit-graph'),handle=lab.getByRole('button',{name:/Band 1,/});await graph.scrollIntoViewIfNeeded();await page.waitForTimeout(120);
 let b=await handle.boundingBox();const x=b.x+b.width/2,y=b.y+b.height/2;
 assert.ok(b.width>=43&&b.height>=43,JSON.stringify(b));
 await page.evaluate(()=>{window.__touchTrace=[];for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])window.addEventListener(type,event=>window.__touchTrace.push({type,target:event.target.className.baseVal||event.target.className,x:event.clientX,y:event.clientY}),true);});
 const cdp=await page.context().newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});
 for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+32*i/8,y:y-44*i/8,id:1}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const gain=Number(await lab.getByLabel('Selected gain',{exact:true}).inputValue());assert.ok(gain>0,JSON.stringify(await page.evaluate(()=>({trace:window.__touchTrace,draft:JSON.parse(localStorage.getItem('audiosage_audio_draft_v2'))}))));
 await lab.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await lab.getByLabel('Selected gain',{exact:true}).inputValue(),'0');
 await lab.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(Number(await lab.getByLabel('Selected gain',{exact:true}).inputValue()),gain);
 await lab.getByRole('button',{name:'Add band on graph',exact:true}).click();await graph.scrollIntoViewIfNeeded();b=await graph.boundingBox();
 await page.touchscreen.tap(b.x+b.width*.45,b.y+b.height*.25);
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')).peqFilters.length===2);
 assert.equal(await lab.getByRole('button',{name:/Band \d+,/}).count(),2);
 await lab.getByLabel('Selected filter type',{exact:true}).selectOption('LS');await lab.getByLabel('Selected Q',{exact:true}).fill('.7');
 await lab.getByLabel('Preset name',{exact:false}).fill('Touch EQ');await lab.getByRole('button',{name:'Save',exact:true}).click();
 await page.reload();await lab.getByRole('button',{name:/^Edit EQ/}).click();
 assert.equal(await lab.getByRole('button',{name:/Band \d+,/}).count(),2);
 const collisions=await lab.locator('[data-axis=frequency]').evaluateAll(nodes=>{const boxes=nodes.map(n=>n.getBoundingClientRect()).sort((a,b)=>a.left-b.left);return boxes.slice(1).some((b,i)=>b.left<boxes[i].right+3);});assert.equal(collisions,false);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 await graph.scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/mobile-eq-touch.png'});
 await browser.close();console.log('PASS 360px touch drag, one-step Undo/Redo, tap band creation, numeric editing, save/reload, non-overlapping labels and 44px handles');
})().catch(e=>{console.error(e);process.exit(1);});
