const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_BROWSER_PATH||'/usr/bin/chromium',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('dialog',d=>d.accept());const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});
 const requests=[];let unavailable=false;
 await page.route('https://generativelanguage.googleapis.com/**',async route=>{
  const request=route.request(),body=request.postDataJSON();requests.push({url:request.url().split('?')[0],body});
  if(unavailable&&request.url().includes('gemini-2.5-flash:')){await route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:{code:404,message:'Model not found'}})});return;}
  const chunk={candidates:[{content:{role:'model',parts:[{text:'Mocked research answer about HD600 FR.'}]},finishReason:'STOP',groundingMetadata:{groundingChunks:[{web:{title:'Cited measurement',uri:'https://example.com/cited'}},{web:{title:'Unused source',uri:'https://example.com/unused'}}],groundingSupports:[{groundingChunkIndices:[0],segment:{startIndex:0,endIndex:20,text:'Mocked research answer'}}]}}]};
  await route.fulfill({status:200,contentType:'text/event-stream',body:'data: '+JSON.stringify(chunk)+'\n\n'});
 });
 await page.goto(process.env.AUDIOSAGE_PRODUCTION_URL||'http://127.0.0.1:3001');
 await page.getByText('AI setup needed',{exact:true}).waitFor();
 const nav=async name=>{await page.locator('.workspace-sidebar').getByRole('button',{name,exact:false}).click();await page.waitForTimeout(100);};
 await nav('Settings & data');await page.getByLabel('Gemini API key',{exact:true}).fill('TEST_PRODUCTION_PERSONAL_KEY');await page.getByRole('button',{name:'Test Connection',exact:true}).click();await page.getByText(/verified streaming and grounding request/).waitFor();
 assert.ok(requests[0].url.includes('streamGenerateContent'));assert.ok(requests[0].body.tools.some(t=>t.googleSearch));
 await nav('Research notes');await page.getByRole('button',{name:'Add note',exact:true}).click();await page.getByLabel('Edit User note',{exact:true}).fill('HD600 FR has warm mids. This is a user note.');await page.waitForTimeout(100);
 unavailable=true;await nav('Research assistant');await page.getByLabel('Message the research assistant',{exact:true}).fill('What does my HD600 FR note say?');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('Mocked research answer about HD600 FR.',{exact:true}).waitFor();await page.waitForTimeout(100);
 const modelSelect=page.locator('.model-select select');assert.equal(await modelSelect.inputValue(),'gemini-2.5-flash');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('audiosage_chats_v1')));const answer=saved.flatMap(s=>s.messages).find(m=>m.role==='model');assert.equal(answer.requestedModel,'gemini-2.5-flash');assert.equal(answer.answeringModel,'gemini-2.5-pro');assert.ok(answer.contextSupplied.some(r=>r.kind==='user-note'));assert.equal(answer.groundingSources.length,1);assert.equal(answer.groundingSources[0].title,'Cited measurement');
 await nav('Research notes');await page.getByRole('checkbox',{name:'Enabled',exact:true}).uncheck();await nav('Research assistant');await page.getByLabel('Message the research assistant',{exact:true}).fill('Tell me about that HD600 FR note again.');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.waitForFunction(()=>{const chats=JSON.parse(localStorage.getItem('audiosage_chats_v1')||'[]');return chats.flatMap(s=>s.messages).filter(m=>m.role==='model'&&!m.isThinking).length===2;});
 const last=await page.evaluate(()=>JSON.parse(localStorage.getItem('audiosage_chats_v1')).flatMap(s=>s.messages).filter(m=>m.role==='model').at(-1));assert.ok(!last.contextSupplied.some(r=>r.kind==='user-note'));
 const generated=requests.filter(r=>r.url.includes('gemini-2.5-pro:'));assert.ok(generated[0].body.systemInstruction.parts[0].text.includes('HD600 FR has warm mids'));assert.ok(!generated.at(-1).body.systemInstruction.parts[0].text.includes('HD600 FR has warm mids'));
 await nav('Equalizer');await page.getByRole('button',{name:'New preset',exact:true}).click();await page.getByLabel('Preset name',{exact:false}).fill('Production manual');await page.getByLabel('Gain at 1000 Hz',{exact:true}).fill('3');await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForTimeout(100);await page.reload();await nav('Equalizer');assert.equal(await page.getByLabel('Preset name',{exact:false}).inputValue(),'Production manual');assert.equal(await page.getByLabel('Gain at 1000 Hz',{exact:true}).inputValue(),'3');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download .txt',exact:true}).click();const file=await download;const text=Buffer.concat(await(await file.createReadStream()).toArray()).toString();assert.match(text,/intended sample rate 48000/);assert.match(text,/Preamp: -/);
 const bridge=await page.request.get('http://127.0.0.1:3001/api/apo/status');assert.notEqual(bridge.headers()['content-type'],'application/json');
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS production lazy loading, browser personal key, mocked streaming/grounding capability, unavailable-model fallback preserving selection, per-answer supplied context/model/cited-only sources, disabled-source exclusion, manual save/refresh/export, hosted APO distinction');
})().catch(e=>{console.error(e);process.exit(1);});
