const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
  const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_BROWSER_PATH||'/usr/bin/chromium',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('dialog',d=>d.accept());
  await page.route('https://generativelanguage.googleapis.com/**',r=>r.abort());
  await page.goto('http://127.0.0.1:3000');
  await page.evaluate(async()=>{const {DEFAULT_PROFILE}=await import('/types.ts');localStorage.setItem('audiosage_profile_v1',JSON.stringify({...DEFAULT_PROFILE,eqLibrary:[],gearLibrary:[{id:'qa-gear',name:'Test headphones',type:'Headphone',status:'owned',addedAt:1}]}));});await page.reload();
  const nav=async label=>{await page.locator('.workspace-sidebar').getByRole('button',{name:label,exact:false}).click();await page.waitForTimeout(100);};
  const draft=()=>page.evaluate(async()=>(await import('/store/audioWorkspace.ts')).audioWorkspace.getSnapshot());
  await nav('Equalizer');
  await page.locator('input[accept=".csv,.tsv,.txt"]').setInputFiles({name:'journey.csv',mimeType:'text/csv',buffer:Buffer.from('Frequency,SPL\n20,82\n50,82\n100,80\n200,79\n500,78\n1000,80\n2000,85\n4000,81\n8000,86\n16000,76\n20000,70')});
  await page.getByRole('button',{name:'Edit generated EQ',exact:true}).click();
  let state=await draft();assert.ok(state.draft.measurementRef);assert.ok(state.draft.peqFilters.length);assert.ok(state.draft.originalFit.evaluatedPoints>0);
  const ref=state.draft.measurementRef;
  await page.waitForTimeout(150);
  const handle=page.getByRole('button',{name:/Band 1,/});await handle.scrollIntoViewIfNeeded();await handle.focus();await page.keyboard.press('ArrowUp');await page.waitForTimeout(100);
  let edited=await draft();assert.equal(edited.draft.peqFilters[0].gain,state.draft.peqFilters[0].gain+.5);
  await handle.scrollIntoViewIfNeeded();
  const before=edited.undoCount, bounds=await handle.boundingBox();
  await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);
  await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2+35,bounds.y+bounds.height/2-15,{steps:8});await page.mouse.up();
  const dragged=await draft();assert.equal(dragged.undoCount,before+1);assert.notDeepEqual(dragged.draft.peqFilters,edited.draft.peqFilters);
  await page.evaluate(async()=>{(await import('/store/audioWorkspace.ts')).audioWorkspace.undo();});assert.deepEqual((await draft()).draft.peqFilters,edited.draft.peqFilters);
  await handle.scrollIntoViewIfNeeded();
  const b2=await handle.boundingBox();await page.mouse.move(b2.x+b2.width/2,b2.y+b2.height/2);await page.mouse.down();await page.mouse.move(b2.x+b2.width/2+30,b2.y+b2.height/2-20);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await draft()).draft.peqFilters,edited.draft.peqFilters);
  await page.getByLabel('Preset name',{exact:false}).fill('Measurement journey');
  await page.getByLabel('Assigned gear',{exact:true}).selectOption('qa-gear');
  await page.getByLabel('Preamp mode',{exact:false}).selectOption('manual');await page.getByLabel('Requested preamp',{exact:true}).fill('-12');
  await page.getByRole('button',{name:'Save',exact:true}).click();await page.waitForTimeout(100);
  state=await draft();assert.equal(state.draft.dirty,false);const savedId=state.draft.editingPresetId;
  await page.getByRole('button',{name:'Save as copy',exact:true}).click();await page.waitForTimeout(100);assert.notEqual((await draft()).draft.editingPresetId,savedId);
  await nav('Overview');await page.reload();await nav('Equalizer');await page.waitForTimeout(150);
  state=await draft();assert.equal(state.draft.measurementRef,ref);assert.equal(state.draft.gearId,'qa-gear');assert.equal(state.draft.requestedPreamp,-12);assert.deepEqual(state.draft.peqFilters,edited.draft.peqFilters);
  await page.getByLabel('Preset name',{exact:false}).waitFor();
  assert.equal(await page.getByLabel('Preset name',{exact:false}).inputValue(),'Measurement journey');
  await page.getByRole('button',{name:/Band 1,/}).scrollIntoViewIfNeeded();
  await page.screenshot({path:'artifacts/workspace-measurement-editor.png',fullPage:true});
  console.log('PASS measurement -> fitting -> keyboard/drag/cancel/undo -> gear/save/copy -> navigate/refresh/reopen with source links and requested preamp');
  const storage=await page.evaluate(async()=>{
    const ws=await import('/store/audioWorkspace.ts'), backups=await import('/utils/workspaceBackup.ts'), lab=await import('/store/labStore.ts');
    const profile=JSON.parse(localStorage.getItem('audiosage_profile_v1'));
    localStorage.setItem('audiosage_api_key','TEST_PERSONAL_KEY_MUST_NOT_LEAK');
    const backup=await backups.createWorkspaceBackup(profile,[],[]);
    const serialized=JSON.stringify(backup);
    const results={noKey:!serialized.includes('TEST_PERSONAL_KEY_MUST_NOT_LEAK'),measurementCount:backup.audio.measurements.length};
    const validated=backups.validateBackup(backup);await backups.restoreWorkspaceBackup(validated);
    results.restoredRef=ws.audioWorkspace.getSnapshot().draft.measurementRef;
    const invalids=[{...backup,version:999},{...backup,audio:{...backup.audio,draft:{...backup.audio.draft,sampleRate:1}}},{...backup,profile:{...profile,eqLibrary:[profile.eqLibrary[0],profile.eqLibrary[0]]}},{...backup,audio:{...backup.audio,measurements:[backup.audio.measurements[0],backup.audio.measurements[0]]}}];
    results.rejected=invalids.map(v=>{try{backups.validateBackup(v);return false;}catch{return true;}});
    const legacy=backups.validateBackup({profile,chats:[],knowledgeBase:[]});
    results.legacyVersions=[1,2].every(version=>backups.validateBackup({version,profile,chats:[],knowledgeBase:[]}).profile.name===profile.name);
    const legacyPeq=ws.draftFromPreset({id:'legacy-peq',name:'Legacy PEQ',hardware:'Legacy',type:'Parametric',bands:'Preamp: -9 dB\nFilter 1: OFF PK Fc 1000 Hz Gain 4 dB Q 1.4',timestamp:1});results.legacyPreamp=legacyPeq.requestedPreamp;results.legacyEnablement=legacyPeq.peqFilters[0].enabled;results.legacyPreserved=legacy.profile.eqLibrary.length===profile.eqLibrary.length;
    const missing=structuredClone(backup);missing.audio.measurements=[];results.missing=backups.missingBackupReferences(missing).length;backups.recoverMissingReferences(missing);results.manualRecovery=missing.audio.draft.measurementRef===null;
    const originalSet=Storage.prototype.setItem, previous=localStorage.getItem('audiosage_audio_draft_v2');
    Storage.prototype.setItem=function(key,value){if(key==='audiosage_audio_draft_v2')throw new DOMException('Simulated quota','QuotaExceededError');return originalSet.call(this,key,value);};
    ws.audioWorkspace.update({presetName:'In-memory recovery'});results.retainedInMemory=ws.audioWorkspace.getSnapshot().draft.presetName==='In-memory recovery';results.failedWriteError=ws.audioWorkspace.getSnapshot().error;results.previousPreserved=localStorage.getItem('audiosage_audio_draft_v2')===previous;
    Storage.prototype.setItem=originalSet;ws.audioWorkspace.retry();results.retrySaved=JSON.parse(localStorage.getItem('audiosage_audio_draft_v2')).presetName==='In-memory recovery';
    let once=true;Storage.prototype.setItem=function(key,value){if(key==='audiosage_chats_v1'&&once){once=false;throw new DOMException('Simulated failed restore','QuotaExceededError');}return originalSet.call(this,key,value);};
    const beforeProfile=localStorage.getItem('audiosage_profile_v1');try{await backups.restoreWorkspaceBackup(backup);results.restoreFailure=false;}catch{results.restoreFailure=true;}finally{Storage.prototype.setItem=originalSet;}
    const recovered=await backups.previousWorkspaceBackup();results.previousRecoveryValid=recovered.profile.name===profile.name;
    results.rollback=localStorage.getItem('audiosage_profile_v1')===beforeProfile;results.recoveryPreserved=!!localStorage.getItem('audiosage_restore_recovery_v3');
    const a=lab.labStore.getSnapshot().curves[0];lab.labStore.addCurve({...a,id:'hidden',isTarget:false,visible:false});lab.labStore.toggleSolo(a.id);lab.labStore.toggleSolo(a.id);results.soloPreserved=!lab.labStore.getSnapshot().curves.find(c=>c.id==='hidden').visible;
    return results;
  });
  assert.ok(storage.noKey);assert.equal(storage.measurementCount,1);assert.equal(storage.restoredRef,ref);assert.ok(storage.rejected.every(Boolean));assert.ok(storage.legacyPreserved&&storage.legacyVersions);assert.equal(storage.legacyPreamp,-9);assert.equal(storage.legacyEnablement,false);assert.ok(storage.missing>0);assert.ok(storage.manualRecovery);assert.ok(storage.retainedInMemory&&storage.previousPreserved&&storage.retrySaved);assert.match(storage.failedWriteError,/write failed/);assert.ok(storage.previousRecoveryValid&&storage.restoreFailure&&storage.rollback&&storage.recoveryPreserved&&storage.soloPreserved);
  console.log('PASS complete backup/restore, legacy preservation, unknown-version/numeric/duplicate rejection, missing-link manual recovery, quota and interrupted restore rollback, credential exclusion, Solo visibility');
  await nav('Graph lab');const lab=page.getByRole('dialog',{name:'Graph lab',exact:true});
  await lab.getByText('Advanced',{exact:true}).click();assert.ok(await lab.locator('.lab-advanced').evaluate(e=>e.open));await page.keyboard.press('Escape');assert.equal(await lab.count(),1);assert.equal(await lab.locator('.lab-advanced').evaluate(e=>e.open),false);
  const options=lab.getByRole('button',{name:/Options for/}).first();await options.click();let panel=page.locator('.portal-popover');await panel.waitFor();let box=await panel.boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.y+box.height<=1000);
  await page.keyboard.press('ArrowDown');await page.keyboard.press('Escape');assert.equal(await panel.count(),0);assert.equal(await lab.count(),1);assert.ok(await options.evaluate(e=>document.activeElement===e));await page.keyboard.press('Escape');assert.equal(await lab.count(),0);
  await nav('Graph lab');await page.setViewportSize({width:390,height:844});await page.getByText('Curves',{exact:true}).click();await page.getByRole('button',{name:/Options for/}).first().click();panel=page.locator('.portal-popover');box=await panel.boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=390&&box.y+box.height<=844);await page.keyboard.press('Escape');await page.keyboard.press('Escape');
  console.log('PASS desktop/mobile portal bounds, keyboard navigation, focus restoration and one-surface Escape');
  const config=await page.evaluate(async()=>{const {resolveApiKey,classifyAiError}=await import('/services/aiConfig.ts');return {source:resolveApiKey().source,errors:['401','404','429','Failed to fetch','Invalid request'].map(x=>classifyAiError(new Error(x)))};});assert.equal(config.source,'Browser personal key');assert.deepEqual(config.errors,['credential','model','quota','network','request']);
  await page.evaluate(()=>localStorage.setItem('audiosage_audio_draft_v2','{"version":999}'));await page.reload();await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.locator('.workspace-sidebar').getByRole('button',{name:'Equalizer',exact:true}).click();await page.getByRole('alert').filter({hasText:'Saved Audio draft'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('audiosage_audio_draft_v2')),'{"version":999}');
  console.log('PASS key source/classification and unknown draft recovery preserves original');
  assert.deepEqual(errors,[]);await browser.close();console.log('ALL WORKSPACE JOURNEYS PASSED');
})().catch(e=>{console.error(e);process.exit(1);});
